    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
                <a href="#">看这儿！</b></a>
                <a href="/page/whh5_addPost.php" class="btn btn-small pull-right btn-success" style="margin-top: 0px" ><i class="icon-plus"></i></a>
              </h4>
          </div>
        </div>
      </div>
    </div>