	<div class="row" style="border: 1px solid #787878;border-radius: 6px; border-left: 3px solid #ff0000;margin-left: 5px;margin-right: 5px;margin-bottom: 10px;padding: 5px;">	
		<div class="span12" style="margin-top: 40px;margin-left: -20px;margin-right:-20px ">
          <div class="row">
            <div class="span12">
              <h3><br/><br/><?php echo $content; ?></h3>
            </div>
          </div>
          <div class="row">
            <div class="span12">
              <div class="pull-right"><?php echo ml_tool_standardShow::time($_ctime); ?> <a href="href">小顶</a></div>
            </div>
          </div>
        </div>
    </div>