	
		<div class="span12" style="border: 1px solid #787878;border-radius: 6px; border-left: 3px solid #ff0000;padding: 5px;">
          <div class="row">
            <div class="span12">
              <h3><br/><br/><?php echo $content; ?></h3>
            </div>
          </div>
          <div class="row">
            <div class="span12">
              <div class="pull-right"><?php echo ml_tool_standardShow::time($_ctime); ?> <a href="href">小顶</a></div>
            </div>
          </div>
        </div>
  