<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
                <a href="#"><b>看这儿！</b><em id="position"></em></a>
                <a href="/page/whh5_here.php" class="btn btn-small pull-right" style="margin-top: 0px" ><i class="icon-arrow-left icon-white"></i>回这儿</a>
              </h4>
          </div>
        </div>
      </div>
    </div>




    <div class="container-fluid" style="margin-top: 50px;">
      <div id="divCondition" style="border: 1px solid #bcbcbc;"></div>
      <a href="#myModal" role="button" class="pull-right" data-toggle="modal">+条件</a>
      <textarea rows="5" id="textContent" class="input-large"></textarea><br/>
      <span>可见范围：</span>
      <div class="btn-group" id="btnAccuracy">
      <button class="btn active" value=0>正常</button>
      <button class="btn" value=1>精确</button>
      <button class="btn" value=2>超大</button>
      </div>
      <div><button id="btnSave" href="#" class="pull-right btn btn-success">保存</button></div>
    </div>
    <div class="container-fluid" style="background-color: #454545;border-top: 3px solid #353535;bottom: 0;position: relative;">
      <div>这里是：lat:<span id="latitude"></span> long:<span id="longitude"></span></div>
      <div id="position"></div>
    </div>
    





      <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 id="myModalLabel">谁能看到?</h4>
        </div>
        <div class="modal-body">
          <ul class="nav nav-tabs">
          <li class="active"><a href="#home" data-toggle="tab"><i class="icon-user icon-white"></i></a></li>
          <li><a href="#profile" data-toggle="tab" id="tabMyPost"><i class="icon-eye-open icon-white"></i></a></li>
          
          </ul>
               
          <div class="tab-content">
          <div class="tab-pane active" style="height: 200px;" id="home">
            <ul>
              <li>
                可见性别：
                <div class="btn-group" id="btnSexCondition">
                <button class="btn active" value=0>不限制</button>
                <button class="btn" value=1>只限女生</button>
                <button class="btn" value=2>只限男生</button>
                </div>  
              </li>
            
          </div>
          <div class="tab-pane" id="profile">
            <small>看到过我最近的留言</small>
            <ul style="height: 150px" id="ulMyPost">
            </ul>
          </div>
          
            
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
          <button class="btn btn-primary">增加条件</button>
        </div>
      </div>  
    



<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>
<script type="text/javascript">
  
    if(navigator.geolocation) {
        navigator.geolocation.watchPosition(geoLocationCallback, handleLocationError, {maximumAge:20000});
    }
  
  function geoLocationCallback(position)
  {
    latNum = new Number(position.coords.latitude);
    longNum = new Number(position.coords.longitude);
    scope.latitude=latNum.toFixed(7);
    scope.longitude=longNum.toFixed(7);
    if (position.coords.accuracy >= 500) {
        return;
    }

    $('#latitude').html(scope.latitude);
    $('#longitude').html(scope.longitude);

    if(!scope.loadposition){
      
      $.get(
          '/public/h5/api/wh_hereGetPosition.php?latitude='+scope.latitude+'&longitude='+scope.longitude,
          function(result){
            scope.loadposition=1;

            eval('rs='+result+'');
            
            $('#position').html(rs.data.address);
          }
        );

    }
  }



  function handleLocationError(error) {
        switch(error.code)
        {
        case 0:
        //  updateStatus("尝试获取您的位置信息时发生错误：" + error.message);
          break;
        case 1:
       //   updateStatus("用户拒绝了获取位置信息请求。");
          break;
        case 2:
    //    updateStatus("浏览器无法获取您的位置信息：" + error.message);
          break;
        case 3:
     //     updateStatus("获取您位置信息超时。");
          break;
        }
    }
  
  if (window.DeviceMotionEvent) {   
    window.addEventListener('devicemotion',deviceMotionHandler, false);    
  }

  var last_update = 0;      
  var x=y=z=last_x=last_y=last_z=0;  
  function deviceMotionHandler(eventData){
    var acceleration =eventData.accelerationIncludingGravity;    
       
    var curTime = new Date().getTime();   
    if ((curTime - last_update)> 100) {    
        var diffTime = curTime -last_update;      
        last_update = curTime;          
        x = acceleration.x;   
        y = acceleration.y;     
        z = acceleration.z;     
        var speed = Math.abs(x +y + z - last_x - last_y - last_z) / diffTime * 10000;     
          $('#xxx').empty().html(speed);
        if (speed > 3000) {      
          alert('xx');
        }      
        last_x = x;      
        last_y = y;      
        last_z = z;      
        }

  }

  $('#btnSave').click(function(){
    content = $('#textContent').val();
    
    condition = {};
    sexCondition = $('#btnSexCondition .active').attr('value');
    
    if(sexCondition > 0){
      condition.sex= sexCondition;
    }

      condition.viewdGpid = new Array();
    $('.aViewdCondition').each(function(){
      if($(this).attr('ischeck') == 1){
        condition.viewdGpid.push($(this).attr('gpid'));
      }
    });

    data = {
      'latitude':scope.latitude,
      'longitude':scope.longitude,
      'content':content,
      'accuracy':$('#btnAccuracy .active').attr('value'),
      'condition':condition
    };
    $.post(
        '/public/h5/api/wh_addGeoPost.php',
        data,
        function(rs){
          alert('发布成功');    

        }
      );

  });
  $('#btnCondition').click(function(){
    $('#divCondition').html("<br/>xxxxx</br>");
  });
  
  $('#tabMyPost').click(function(){
    if(!scope.myPost){
      $.get('/public/h5/api/wh_myPost.php',function(result){
        eval('rs='+result);
        
        scope.myPost=rs.data.rows;
        myPostLi = '';

        for(k in scope.myPost){
          row = scope.myPost[k];
          myPostLi+='<li>'+row.content+' <a href="#" class="text-success aViewdCondition" gpid="'+row.gpid+'" ischeck="0">+条件</a></li>';
        }

        $('#ulMyPost').append(myPostLi);

        $('.aViewdCondition').click(function(){
          
          if($(this).attr('ischeck') == 1){
            $(this).text('+条件').removeClass('text-error').addClass('text-success').attr('ischeck' , 0);
          }else{
            $(this).text('-取消').addClass('text-error').removeClass('text-success').attr('ischeck' , 1);
          }
        });
      });
    }
  });

  $('#btnAccuracy .btn').click(function(){
    $('#btnAccuracy .btn').each(function(){
      $(this).removeClass('active');
    });
    $(this).addClass('active');

  });
  $('#btnSexCondition .btn').click(function(){
    $('#btnSexCondition .btn').each(function(){
      $(this).removeClass('active');
    });
    $(this).addClass('active');

  });


</script>