<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>
<style>
.postBg{
  background-image: url('<?php echo $this->_uri_dir ?>/img/here_bg.jpg')
}
</style>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <div style="margin-left: 20px;margin-right: 20px;">
              <h4>
                <a href="#"><b>看这儿！</b><em id="position"></em></a>
                <a href="/page/whh5_addPost.php" class="btn btn-small pull-right btn-success" style="margin-top: 0px" ><i class="icon-plus"></i></a>
                <a href="javascript:;" class="btn btn-small pull-right" style="margin-top: 0px" id="fff" ><i class="icon-refresh"></i></a>
              </h4>
          </div>
        </div>
      </div>
    </div>

<br/><br/>
    <div class="container-fluid postBg">
      <div class="row" id="geoPost">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      </div>
    </div>

    <div class="container-fluid" style="display: none" id="divComment">
      <div class="row">

        <h3 style="border-bottom: 1px solid #c8c8c8">评论<a href="javascript:;" class="btn btn-mini pull-right" style="margin-top: 12px;" ><i class="icon-plus"></i></a></h3>
        <ul>

        </ul>
      </div>
    </div>

    <div id="latitude"></div>
    <div id="longitude"></div>
    <div id="xxx"></div>
<?php echo memory_get_peak_usage()/1024/1024;  ?>
<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>
<script type="text/javascript">
  
    if(navigator.geolocation) {
        navigator.geolocation.watchPosition(geoLocationCallback, handleLocationError, {maximumAge:20000});
    }
  
  function geoLocationCallback(position)
  {
    latNum = new Number(position.coords.latitude);
    longNum = new Number(position.coords.longitude);
    scope.latitude=latNum.toFixed(5);
    scope.longitude=longNum.toFixed(5);
    if (position.coords.accuracy >= 500) {
        return;
    }

    $('#latitude').html(scope.latitude);
    $('#longitude').html(scope.longitude);

    if(!scope.loadposition){
      
      $.get(
          '/public/h5/api/wh_hereGetPosition.php?latitude='+scope.latitude+'&longitude='+scope.longitude,
          function(result){
            scope.loadposition=1;

            eval('rs='+result+'');
            $('#position').html(rs.data.address);
          }
        );

    }
  }
  function handleLocationError(error) {
        switch(error.code)
        {
        case 0:
        //  updateStatus("尝试获取您的位置信息时发生错误：" + error.message);
          break;
        case 1:
       //   updateStatus("用户拒绝了获取位置信息请求。");
          break;
        case 2:
    //    updateStatus("浏览器无法获取您的位置信息：" + error.message);
          break;
        case 3:
     //     updateStatus("获取您位置信息超时。");
          break;
        }
    }
  
  if (window.DeviceMotionEvent) {   
    window.addEventListener('devicemotion',deviceMotionHandler, false);    
  }

  var last_update = 0;      
  var x=y=z=last_x=last_y=last_z=0;  
  function deviceMotionHandler(eventData){
    var acceleration =eventData.accelerationIncludingGravity;    
       
    var curTime = new Date().getTime();   
    if ((curTime - last_update)> 100) {    
        var diffTime = curTime -last_update;      
        last_update = curTime;          
        x = acceleration.x;   
        y = acceleration.y;     
        z = acceleration.z;     
        var speed = Math.abs(x +y + z - last_x - last_y - last_z) / diffTime * 10000;     
          $('#xxx').empty().html(speed);
        if (speed > 1000) {      
          
          loadPost();
          

        }      
        last_x = x;      
        last_y = y;      
        last_z = z;      
        }

  }

  function loadPost(){
    $.get('/public/h5/api/wh_hereGetPost.php?latitude='+scope.latitude+'&longitude='+scope.longitude,function(result){
            eval('rs='+result);
            $('#geoPost').parent().removeClass('postBg');
            $('#geoPost').hide(200,function(){
              $('#geoPost').html(rs.data.html);
              if(rs.data.isok == 1){
                $('#divComment').show();
              }  
              $('#geoPost').show(1000);
            });
            
            
          });
  }

  $('#fff').click(function(){
    loadPost();

  });
  
</script>