<?php include($this->_tpl_dir.'/_tpl_htmlHeader.phtml'); ?>

<?php include($this->_tpl_dir.'/_tpl_navArticlelist.phtml'); ?>

<br/><br/><br/><br/>
    <div class="container-fluid" style="margin-top: 40px;margin-left: -20px;margin-right:-20px ">
    
    <div id="latitude"></div>
    <div id="longitude"></div>
    <div id="xxx"></div>
    </div>
<?php echo memory_get_peak_usage()/1024/1024;  ?>
<?php include($this->_tpl_dir.'/_tpl_htmlFooter.phtml'); ?>
<script type="text/javascript">
  
    if(navigator.geolocation) {
        navigator.geolocation.watchPosition(geoLocationCallback, handleLocationError, {maximumAge:20000});
    }
  
  function geoLocationCallback(position)
  {
    latNum = new Number(position.coords.latitude);
    longNum = new Number(position.coords.longitude);
    scope.latitude=latNum.toFixed(5);
    scope.longitude=longNum.toFixed(5);
    if (position.coords.accuracy >= 500) {
        return;
    }

    $('#latitude').html(scope.latitude);
    $('#longitude').html(scope.longitude);
  }
  function handleLocationError(error) {
        switch(error.code)
        {
        case 0:
        //  updateStatus("尝试获取您的位置信息时发生错误：" + error.message);
          break;
        case 1:
       //   updateStatus("用户拒绝了获取位置信息请求。");
          break;
        case 2:
    //    updateStatus("浏览器无法获取您的位置信息：" + error.message);
          break;
        case 3:
     //     updateStatus("获取您位置信息超时。");
          break;
        }
    }
  
  if (window.DeviceMotionEvent) {   
    window.addEventListener('devicemotion',deviceMotionHandler, false);    
  }

  var last_update = 0;      
  var x=y=z=last_x=last_y=last_z=0;  
  function deviceMotionHandler(eventData){
    var acceleration =eventData.accelerationIncludingGravity;    
       
    var curTime = new Date().getTime();   
    if ((curTime - last_update)> 100) {    
        var diffTime = curTime -last_update;      
        last_update = curTime;          
        x = acceleration.x;   
        y = acceleration.y;     
        z = acceleration.z;     
        var speed = Math.abs(x +y + z - last_x - last_y - last_z) / diffTime * 10000;     
          $('#xxx').empty().html(speed);
        if (speed > 3000) {      
          alert('xx');
        }      
        last_x = x;      
        last_y = y;      
        last_z = z;      
        }

  }

  
  
</script>